/* =========================================================
   VOLTICA STORE
   PRODUCT DATABASE
   GENERATED BY ADMIN PRODUCT MANAGER
   ========================================================= */

"use strict";


window.volticaProducts = [

    {
        "id": "anker-soundcore-space-q45-wireless-headphones-selected-by-voltica-store",

        "sku": "VLT-AUD-Q45-001",

        "name": "Anker Soundcore Space Q45 Wireless Headphones | Selected by Voltica Store",

        "category": "PREMIUM AUDIO",

        "badge": "LIMITED",

        "price": 189.99,

        "referencePrice": 219.99,

        "cost": 153.65,

        "shipping": 6.14,

        "shortDescription": "Experience industry-leading adaptive active noise cancellation, stunning Hi-Res wireless audio powered by LDAC, and an exceptional 50-hour battery life. Hand-picked and curated by Voltica Store for ultimate comfort and premium sound performance.",

        "description": "Step into your own private acoustic sanctuary with the Anker Soundcore Space Q45, expertly curated and selected by Voltica Store for discerning audiophiles and modern creators. Whether you are navigating a bustling downtown commute, locking in for a deep-work session, or unwinding with your favorite tracks, these headphones redefine what it means to truly listen.\n\nEngineered with a next-generation adaptive active noise-cancelling (ANC) system, the Space Q45 intelligently targets and blocks out up to 98% of ambient noise — from the rumble of airplane engines to the chatter of a busy coffee shop. Prefer to stay aware of your surroundings? Switch effortlessly between multiple transparency modes tailored to your environment without ever needing to take your headphones off.\n\nBeneath the sleek exterior lies certified Hi-Res Audio Wireless support powered by LDAC technology, transmitting three times more data than standard Bluetooth codecs to deliver breathtaking, studio-quality sound with rich detail and deep bass. Combined with an industry-leading 50-hour battery life with ANC turned on and ultra-comfortable ergonomic memory foam earcups wrapped in soft leatherette, the Space Q45 ensures your listening experience remains uninterrupted, luxurious, and fatigue-free from morning until night. Elevate your daily soundtrack with a curated tech essential designed for unmatched performance.",

        "features": [

            "Adaptive Active Noise Cancelling (ANC): Intelligently targets and blocks up to 98% of external sounds, featuring customized modes optimized for indoor, outdoor, and travel environments.",

            "Hi-Res Audio Wireless via LDAC: Transmits three times more data than standard Bluetooth connections to deliver pristine, high-resolution audio with rich instrumentation and deep bass.",

            "50-Hour Extended Battery Life: Provides up to 50 hours of continuous playtime with ANC turned on, and up to 65 hours in standard mode to keep you powered through days of use.",

            "Ergonomic & Lightweight Design: Built with a refined aesthetic, a comfortable pressure-relieving headband, and ultra-soft memory foam earcups for all-day listening comfort.",

            "Customizable Sound & Transparency: Tailor your audio profile using the Soundcore app's 8-band EQ and switch seamlessly between transparency modes to stay connected to the world around you."

        ],

        "specifications": {

            "Bluetooth Version": "Bluetooth 5.3",

            "Audio Codecs": "LDAC, AAC, SBC",

            "Playtime": "Up to 50 hours (ANC on) / Up to 65 hours (ANC off)",

            "Fast Charging": "5 minutes charge for 4 hours of playtime",

            "Driver Size": "40mm customized double-layer diaphragm drivers",

            "Frequency Response": "20Hz - 40kHz (Hi-Res Wired & Wireless)",

            "Connectivity Range": "Up to 15 meters / 50 feet (Multipoint connection supported)",

            "Charging Port": "USB Type-C",

            "Weight": "292 g"

        },

        "images": [

            "assets/images/Q45.1.jpg",

            "assets/images/Q45.2.jpg",

            "assets/images/Q45.3.jpg",

            "assets/images/Q45.4.jpg",

            "assets/images/Q45.6.jpg"

        ],

        "colors": [

            "Light Blue"

        ],

        "variants": [

            {
                "name": "Light Blue",
                "sku": "VLT-AUD-Q45-LBL"
            }

        ],

        "stripeLink": "https://buy.stripe.com/eVqeVe2hNgILbyoaWK2Ji0j",

        "supplierLink": "https://www.cjdropshipping.com/product/-p-2601110810071616400.html",

        "active": true

    },

    /* =========================================================
       Product name : XReal Air 1S AI Augmented Reality Smart Glasses | Selected by Voltica Store
       ========================================================= */

{
        "id": "xreal-air-1s-ai-augmented-reality-smart-glasses-selected-by-voltica-store",
        "sku": "VLT-XREAL-1S",
        "name": "XReal Air 1S AI Augmented Reality Smart Glasses | Selected by Voltica Store",
        "category": "Lifestyle",
        "badge": "PREMIUM",
        "price": 579.99,
        "referencePrice": 599.99,
        "cost": 464.26,
        "shipping": 30.5,
        "shortDescription": "Step into a new dimension of portable display with the XReal Air 1S AI Augmented Reality Smart Glasses, expertly curated by Voltica Store. These cutting-edge AR glasses project a massive, ultra-bright virtual screen directly into your field of vision, transforming your gaming, movies, and mobile productivity on the go.",
        "description": "Redefine your digital workspace and entertainment setup with the XReal Air 1S AI Augmented Reality Smart Glasses, meticulously hand-picked and curated by Voltica Store for tech enthusiasts and modern innovators. Whether you are gaming on the go, streaming cinematic content, or expanding your mobile workstation, these glasses bridge the gap between the physical and virtual worlds with breathtaking clarity.\nâ€‹Engineered with advanced micro-OLED projection technology, the XReal Air 1S creates a massive, ultra-bright virtual screen with an immersive 52Â° field of view (FOV) that scales effortlessly to match your viewing preferences. Experience stunning visual fidelity featuring automatic electrochromic lenses that intelligently adapt to your lighting environment, ensuring optimal contrast and visibility whether you are indoors or outside in bright daylight.\nâ€‹Equipped with smart AI capabilities, these AR glasses support voice-activated commands for hands-free operation, real-time object recognition, and instant image text translation. Combined with certified TÃœV Rheinland eye comfort features to eliminate fatigue during extended sessions and a universal USB-CDP plug-and-play architecture, the XReal Air 1S delivers seamless, next-level immersion wherever your day takes you.",
        "features": [
            "â€‹Massive Virtual Cinematic Display : Experience an immersive viewing setup with a wide 52Â° field of view (FOV) and an adjustable virtual screen ranging from 31 to 500 inches.",
            "â€‹Automatic Electrochromic Lenses : Built-in smart lenses that automatically adapt to your surrounding environment and clear up seamlessly when you turn your head.",
            "â€‹Advanced AI Capabilities : Integrates voice wake-up commands for hands-free operation, real-time object recognition from photos, and instant text-to-image translation.",
            "â€‹Certified Eye Comfort : Backed by TÃœV Rheinland certifications including 5-star eye comfort, low blue light emissions, and flicker-free technology to reduce strain during long sessions.",
            "â€‹Universal Plug & Play Connectivity : Features seamless USB-CDP connectivity for instant compatibility with smartphones, portable gaming handhelds, tablets, and laptops."
        ],
        "specifications": {
            "â€‹Model": "XREAL Air 1S",
            "â€‹Display Tech": "Advanced Micro-OLED projection",
            "â€‹Field of View (FOV)": "52Â° immersive wide view",
            "â€‹Lens Technology": "Automatic electrochromic adaptive smart lenses",
            "â€‹Chipset": "Advanced X1 chipset (<1% TV distortion)",
            "â€‹Controls": "Intuitive tactile buttons + AI voice assistant wake-up",
            "â€‹Connectivity": "Universal USB-CDP Plug & Play",
            "â€‹Eye Safety & Comfort": "TÃœV Rheinland 5-star certified (Low blue light, flicker-free, anti-fatigue)"
        },
        "images": [
            "assets/images/glass1-1.jpg",
            "assets/images/glass1-2.jpg",
            "assets/images/glass1-3.jpg",
            "assets/images/glass1-4.jpg",
            "assets/images/glass1-5.jpg",
            "assets/images/glass1-6.jpg"
        ],
        "colors": [],
        "variants": [],
        "stripeLink": "https://buy.stripe.com/14A28se0v78bauk4ym2Ji0o",
        "supplierLink": "https://www.alibaba.com/x/B2MGgw?ck=pdp",
        "active": true
           }, 
   /* =========================================================
       Product name : New Wireless Bluetooth Earbuds Neckband Design Noise-canceling Perfect For Workouts
       ========================================================= */

{
        "id": "new-wireless-bluetooth-earbuds-neckband-design-noise-canceling-perfect-for-workouts",
        "sku": "VLT-AUD-Q17-001",
        "name": "Q17 Open-Ear Wireless Earbuds | Selected by Voltica Store",
        "category": "Audio",
        "badge": "BEST SELLER",
        "price": 69.97,
        "referencePrice": 74.97,
        "cost": 30.81,
        "shipping": 6.03,
        "shortDescription": "Experience open-ear comfort and rich spatial sound with the Q17 Open-Ear Wireless Earbuds, hand-picked and curated by Voltica Store. Featuring a sleek electroplated Gem Blue finish, secure ear-hook design, advanced directional audio transmission, and an incredible 45-hour total battery life, these earbuds are built to keep up with your active lifestyle and daily workouts.",
        "description": "â€‹Stay aware of your surroundings while fueling your active lifestyle with the Q17 Open-Ear Wireless Earbuds, expertly curated by Voltica Store. Designed for ultimate versatility, these earbuds combine a striking electroplated Gem Blue finish with an innovative ear-hook design that guarantees a secure, comfortable fit during intense workouts, runs, or all-day work sessions.\nâ€‹Powered by advanced Zhongke Bluetrum chip technology and Bluetooth 5.4 performance, the Q17 utilizes precision directional sound transmission to focus audio directly into your ear canal. This intelligent architectural design minimizes sound leakage while ensuring crisp clarity and deep response through an AI Adaptive Bass Enhancement Algorithm.\nâ€‹Say goodbye to charging anxiety with an impressive total battery life of up to 45 hours supported by a smart digital display charging case. Featuring fast-charging capabilities that give you hours of playback from just a quick charge, intuitive voice control, and crystal-clear call functionality, the Q17 delivers the ultimate balance of style, safety, and audio performance.",
        "features": [
            "â€‹Open-Ear Comfort & Security : Designed with a secure ear-hook style that keeps the earbuds comfortably in place during intense workouts, runs, and daily activities.",
            "â€‹Precision Directional Sound : Features advanced directional audio transmission technology that focuses sound cleanly into the ear canal while minimizing sound leakage.",
            "â€‹AI Bass Enhancement : Equipped with an AI Adaptive Bass Enhancement Algorithm to deliver rich layering and powerful bass response in open sports settings.",
            "â€‹45-Hour Long-Lasting Battery : Delivers up to 45 hours of total playback time with the smart digital display charging case, backed by fast-charging capabilities to eliminate battery anxiety.",
            "â€‹Striking Gem Blue Finish : Styled with a creative, premium electroplated Gem Blue colorway and an intuitive smart charging display case."
        ],
        "specifications": {
            "Product Name": "Q17 Open-Ear Wireless Earbuds (Selected by Voltica Store)",
            "â€‹Colorway": "Gem Blue (Electroplated finish)",
            "â€‹Chip Type": "Zhongke Bluetrum",
            "â€‹Bluetooth Version": "Bluetooth 5.4",
            "â€‹Wearing Style": "Secure ear-hook design (Open-ear / Air conduction)",
            "â€‹Transmission Distance": "Up to 10 meters / 33 feet",
            "â€‹Battery Life": "Up to 45 hours total playback (with digital display charging case)",
            "â€‹Fast Charging": "10 minutes of charge for up to 2 hours of playback",
            "â€‹Audio Technologies": "Directional sound transmission, AI Adaptive Bass Enhancement Algorithm",
            "â€‹Core Functions": "Call functionality, voice control, music playback, digital battery display",
            "â€‹Body Material": "Durable high-grade plastic"
        },
        "images": [
            "assets/images/Screenshot_20260825_184613.jpg",
            "assets/images/Screenshot_20260825_183622.jpg",
            "assets/images/Screenshot_20260825_183350.jpg",
            "assets/images/Screenshot_20260825_184427.jpg",
            "assets/images/Screenshot_20260825_184213.jpg",
            "assets/images/Screenshot_20260825_184032.jpg",
            "assets/images/Screenshot_20260825_183123.jpg",
            "assets/images/Screenshot_20260825_183843.jpg"
        ],
        "colors": [
            "Dark Blue"
        ],
        "variants": [],
        "stripeLink": "https://buy.stripe.com/dRm3cwe0vbor31S4ym2Ji01",
        "supplierLink": "https://www.cjdropshipping.com/product/-p-2512210524261601400.html",
        "active": true
    },
   /* =========================================================
       Product name : Voltica Store Selected - TWS In-Ear Noise Canceling Earbuds with Mic
       ========================================================= */

{
        "id": "voltica-store-selected-tws-in-ear-noise-canceling-earbuds-with-mic",
        "sku": "VLT-AUD-TWS-001",
        "name": "Voltica Store Selected - TWS In-Ear Noise Canceling Earbuds with Mic",
        "category": "Audio",
        "badge": "FEATURED",
        "price": 59.97,
        "referencePrice": 65.99,
        "cost": 36.08,
        "shipping": null,
        "shortDescription": "Immerse yourself in crystal-clear audio and total freedom with the Voltica Store Selected Premium TWS Wireless 5.0 Earbuds. Designed for ultimate versatility, these ultra-lightweight in-ear headphones feature Bluetooth 5.0 multi-point connectivity, smart touch controls, and high-sensitivity microphones with CVC noise cancellation for flawless calls. Whether you are working out, commuting, or relaxing, enjoy up to 24 hours of total playtime supported by a convenient 500mAh magnetic charging dock and customizable ergonomic ear-hooks.",
        "description": "Elevate your daily audio experience with the Voltica Store Selected Premium TWS Wireless Earbuds, meticulously curated for effortless mobility, active lifestyles, and crystal-clear communication. Featuring the latest Wireless 5.0 technology with multi-point connectivity, these earbuds let you effortlessly pair with up to two mobile devices simultaneously, delivering a high-speed, stable transmission range of up to 32.8 feet.\nâ€‹Engineered for absolute comfort and secure stability, the ultra-mini design boasts a compact 10mm diameter complemented by ergonomic ear-hooks and three interchangeable sizes of S/M/L replacement ear tips to ensure a snug, fatigue-free fit for any activity. Whether used in Stereo Mode for immersive music or as a Single Track Mode mono headset for safe driving and calling, the built-in high-sensitive microphone equipped with CVC noise cancellation actively suppresses ambient noise to guarantee pristine voice clarity.\nâ€‹Manage your entire audio journey seamlessly using the intuitive interactive touch control panel: a simple 2-second long press activates your voice assistant, while single-touch commands handle calls, track navigation, and power. Never worry about running out of power thanks to the compact 500mAh magnetic charging dock, which delivers a total of up to 24 hours of combined playback. Complete with an IPX4 water-resistant rating to withstand sweat and outdoor elements, these versatile earbuds are ready to perform wherever your day leads.",
        "features": [
            "â€‹True Wireless Versatility : Features a dual-ear stereo design where the left and right earbuds can be used independently in Single Track Mode or paired together in Stereo Mode.",
            "â€‹Crystal Clear Stereo & CVC Noise Cancellation : Equipped with a high-sensitive microphone and CVC noise cancellation technology to reduce ambient sounds and deliver pristine call quality.",
            "â€‹Intuitive Touch Controls : Built with an interactive biosensor and a multi-functional touch panel for effortless management of calls, music playback, and voice assistants.",
            "â€‹Magnetic Charging Dock : Comes with a compact 500mAh magnetic charging case that charges the earbuds in just 30 minutes and provides up to 24 hours of total playback time.",
            "â€‹Ergonomic Secure Fit & IPX4 Protection : Designed with a mini size, optional ear-hooks, and S/M/L replacement ear tips for stability during workouts, complemented by an IPX4 water-resistant build."
        ],
        "specifications": {
            "â€‹Product Type": "Wireless 5.0 Earbuds",
            "â€‹Bluetooth Version": "Wireless 5.0 with multi-point technology",
            "â€‹Transmission Range": "Up to 10m / 32.8ft (Without barriers)",
            "â€‹Transmission Frequency": "2.4GHz-2.48GHz",
            "â€‹Signal to Noise Ratio (SNR)": "-90dB",
            "â€‹Battery Capacities": "65mAh per earphone / 500mAh rechargeable built-in charging dock",
            "â€‹Playback & Talk Time": "4 hours of music play/talk time per charge (up to 24 hours total with the charging dock)",
            "â€‹Charging Times": "30 minutes for earbuds / 2.5 hours for the charging dock",
            "â€‹Standby Time": "300 hours",
            "â€‹Waterproof Performance": "IPX4 rating",
            "â€‹Materials": "Durable ABS materials",
            "â€‹Dimensions & Weights": "",
            "â€‹Per Earbud Size (with earhook)": "5.5 \\times 4 \\times 1.5 cm (2.17 \\times 1.58 \\times 0.60 inches)",
            "â€‹Per Earphone Weight (with earhook)": "6g / 0.013 lbs",
            "â€‹Charging Dock Size": "8 \\times 5 \\times 3.2 cm (3.15 \\times 1.97 \\times 1.26 inches)",
            "â€‹Charging Dock Weight": "48g / 0.11 lbs"
        },
        "images": [
            "assets/images/1000052411.webp",
            "assets/images/1000052408.webp",
            "assets/images/1000052410.webp",
            "assets/images/1000052409.webp",
            "assets/images/1000052415.webp",
            "assets/images/1000052412.webp",
            "assets/images/1000052414.webp"
        ],
        "colors": [
            "Back"
        ],
        "variants": [],
        "stripeLink": "https://buy.stripe.com/7sY28s5tZ78bbyo9SG2Ji02",
        "supplierLink": "https://www.cjdropshipping.com/product/-p-1996427591927648257.html",
        "active": true
}

];


/* =========================================================
   VOLTICA PRODUCT DATABASE — READY
   ========================================================= */

console.log(
    "VOLTICA: PRODUCTS DATABASE LOADED",
    window.volticaProducts.length,
    "product(s)"
);
